### PR TITLE
ARXIVNG-549 suppress stopwords in author search

### PR DESCRIPTION
**Pull request by erickpeirson**
This also provides a short-term fix for ARXIVNG-543, which is due to erroneous stripping of punctuation characters from author names. The least we can do is process the query in the same way that we prepared the search document. This is *not* a long-term fix.

@eawoods Eager to hear if this improves some of the cases that you were looking at.

### CODE REVIEW

**Comment by erickpeirson** [comment]
Will fix broken test first thing in the AM

**Comment by erickpeirson** [comment]
Will fix broken test first thing in the AM

**Comment by eawoods** [comment]
I tried a couple of things and looked around, to no avail -- when we are both in the office, help me with the incantation for connecting to the production ES that you mentioned yesterday?

**Comment by erickpeirson** [comment]
image

**Comment by erickpeirson** [comment]
image

**Comment by erickpeirson** [comment]
image

**Pull request merged**
