### PR TITLE
ARXIVNG-372 refacted author search as part of simple and advanced search interfaces

### PR DESCRIPTION
**Pull request by erickpeirson**
- Author search is now part of advanced and simple searches
- Instead of directing author searches from abs page, results, to a separate author search interface, we should direct them to the simple search interface with: ``searchtype=author&query={surname}, {forename}`` (implemented already for search results).
- Multiple author names (conjunction) can be specified, delimited with semicolons (``;``).
- Each author name *may* be a literal -- if enclosed in quotes, the search will be for exact matches only. 
- Whether a literal or not, author names with commas are unpacked as ``{surname}, {forename}`` -> ``{forename} {surname}`` before executing queries.
- Includes an opportunistic  first pass at #112 .

Also delivers ARXIVNG-338. To use (from root of repo):

```bash
pip install -U pipenv
pipenv install
pipenv run nose2 --with-coverage     # Here's how you would run the test suite.
pipenv run pylint search     # Here's how you would run pylint
pipenv run mypy --ignore-missing-imports -p search   # And mypy.
pipenv run pydocstyle --convention=numpy --add-ignore=D401 search .   # And pydocstyle.

# When running Python, env vars go before the pipenv invocation, like this:
FLASK_APP=app.py pipenv run python create_index.py     

# So you'd start Flask like this:
FLASK_DEBUG=1 FLASK_APP=app.py pipenv run flask run
```

Note that this doesn't impact how you would run ES on your machine. For example, if you are using ``docker-compose`` you would continue to do this precisely as you did before.

```bash
docker-compose build
docker-compose up
```

### CODE REVIEW

**Comment by eawoods** [comment]
I got through the pipenv steps through "run flask run" (which is just my new favorite thing and I am always going to use the Forrest Gump voice while pasting that in). Works like a charm!
However, the create_index command is coming back with Connection refused, I assume because I didn't start up Elasticsearch. Which method of doing so is the best one for using pipenv? Does pipenv simply replace the "pip install requirements" part, and I would docker-compose up to get elasticsearch as before?

**Comment by eawoods** [comment]
Nevermind, flailed at my own questions, tried docker-compose up and works just fine. Suggestion to make sure that's clear in the instructions - I'm likely to forget the exact steps next time too.

**Comment by eawoods** [comment]
Me again. :)
Will continue testing, but first pass: somehow the paper title field has been dropped from results display, at least on my instance. Scanned the code changes but can't figure out why.

**Comment by erickpeirson** [comment]
pipenv instructions: updated -- better?

**Comment by erickpeirson** [comment]
Huh, that's weird about the title. Here's what it looks like on my machine (with a fresh index):

image

**Comment by eawoods** [comment]
@erickpeirson Must be my index, then, somehow.  Will purge and rebuild index presently.
Mine looks like this: 
screen shot 2018-03-23 at 9 37 55 am

Instructions: much better, thank you!! I will follow along to the best of my ability and cry for help if I get lost. :)

**Comment by eawoods** [comment]
You were on fire with this, @erickpeirson!
Overall, author field is functioning incredibly well AND names in "all fields" are much better also.
I searched for "john" in both author and all fields and got two results in our standard metadata, one with John (and Johnson) as a last name and one with John as a first name. AND....same results on the "all fields" simple search box. Names in quotes (and not in quotes) improved overall.

Wildcards not working with capitalized terms - same as Jref bug.
Otherwise my test cases were all excellent.

Possible note to provide in help text about searching for authors with name1; name2 : this works in Authors field much better than in All Fields (it still works, but with varied results).

**Comment by erickpeirson** [comment]
image

**Comment by erickpeirson** [comment]
image

**Comment by erickpeirson** [comment]
@eawoods What do you think of adding some small help text under the search box describing how to search by author name? E.g. 

Author names: You may search by ``surname, forename`` or ``forename surname``. Separate multiple authors on the same paper with semicolons, e.g. ``Joe Bloggs; Doe, Jane``. Wildcards may also be used, provided that they are not at the beginning of the name.

**Comment by eawoods** [comment]
@erickpeirson Sounds terrific! Are you thinking that particular help text would show underneath the box all the time, or only when Author(s) is selected as the field type? Or all the time? (it might be worth having something like that available for both all fields and authors, or a variant of it)

P.S. there are a couple of author search help lines in the Tips box in my ARXIVNG-384 PR but I am all about the idea of having helper text right underneath the box for authors in particular.

**Pull request merged**
