### PR TITLE
ARXIVNG-262 added support for wildcards and literals

### PR DESCRIPTION
**Pull request by erickpeirson**
Wildcards should now be working in simple, author, and advanced search. 

Basically what I did was...

- Introduce a function in ``search.services.index`` called ``_wildcardEscape`` that escapes any wildcards in string literals, and then checks to see if there are any remaining wildcard characters that should be treated as such.
- Introduce a wrapper for elasticsearch_dsl.Q that returns a "wildcard" query part if the querystring has a wildcard in it, and otherwise falls back to whatever query type was specified.

Made a couple of other minor opportunistic improvements.

### CODE REVIEW

**Comment by erickpeirson** [comment]
Oh, and I added a validator used by the forms in each of the controllers. @eawoods this generates a an error message for the user -- is that too cryptic?

**Comment by eawoods** [comment]
@erickpeirson all the error messages I have seen so far don't look cryptic at all, they are helpful!
Is there a specific message about which you have a concern?

**Comment by erickpeirson** [comment]
@eawoods How about something like this?

image

**Comment by eawoods** [comment]
LOVE IT!

**Comment by eawoods** [comment]
Also I'm surprised that "foo" wasn't in the index.

**Pull request merged**
