### PR TITLE
ARXIVNG-284 updated docs for search

### PR DESCRIPTION
**Pull request by erickpeirson**
Ok, here's a first pass at updating the docs. Please take a look, and let me know what is still missing, what is unclear, etc.

@eawoods How should we incorporate UI documentation into these docs? Separate section (parallel to architecture.rst)? 

To build the service documentation:

```bash
cd docs
pip install -r requirements.txt
make html
```

Open ``docs/build/index.html`` in your browser.

Once we're happy, these could be published via [GitHub pages](https://pages.github.com/) if we so desire. Or elsewhere.

### CODE REVIEW

**Comment by eawoods** [comment]
@erickpeirson UI docs: I know we've talked about this before...in the context of overall system documentation. I think we had said that UI docs should live parallel to architecture docs in the same repo. If so, then yes I'd support having section UI documentation follow the same structure.

Does that still sound reasonable and sense-making? My brain is a bit fried, will read your PR more thoroughly and think about this some more tomorrow morning.

**Comment by erickpeirson** [comment]
Yeah, that's what I remember as well. Just wanted to make sure. Right now we have ``docs/ui`` which has a README and some files. I guess the question is: how to incorporate this into the built docs (architecture, API docs) that are distributed as HTML. Or do we simply provide a link to ``docs/ui`` in the built docs? Does README.md become an rst source (e.g. see ``docs/source/architecture.rst``). 

I'm open to all ideas at this point.

**Comment by eawoods** [comment]
I suppose the right thing to do is to turn the README into .rst and actually write some descriptions of template and CSS conventions.... guess that means I’ve got some writing work on my plate to fill in the full picture. :-)

Yes?

- Liz

On Feb 15, 2018, at 4:35 PM, Erick <notifications@github.com<mailto:notifications@github.com>> wrote:


Yeah, that's what I remember as well. Just wanted to make sure. Right now we have docs/ui which has a README and some files. I guess the question is: how to incorporate this into the built docs (architecture, API docs) that are distributed as HTML. Or do we simply provide a link to docs/ui in the built docs? Does README.md become an rst source (e.g. see docs/source/architecture.rst).

I'm open to all ideas at this point.

**Comment by erickpeirson** [comment]
Good idea to integrate in some way. But let's not create a mountain of extra work.

**Comment by eawoods** [comment]
How about just a small hillock - I'll timebox an hour to write up any relevant notes on anything that's changed or important UI decisions we made, and we can do the .rst conversion (maybe together so that I can learn a bit?).

I am not super invested in this plan and am happy to defer as you see fit.

**Comment by JaimieMurdock** [comment]
For converting md<->rst, `pandoc` is a good option.

**Comment by erickpeirson** [comment]
That seems reasonable to me

**Comment by eawoods** [comment]
Okay, so after reading through the documentation I have the following comments:

1) Solid and concise description, and in general readable even for kinda-sorta laypeople.
2) Quality goals: can/should we start adding in accessibility quality goals here? Perhaps not as unit tests, but at least as a formal release requirement. Just a thought, and I know that UI testing integration has been an ongoing conversation.
3) Components: Search service - final paragraph "because we expect search functionality to change dramatically in the future" perhaps would be better phrased as "user interface will change dramatically to support the incorporation of further features and enhancements"?  Is it a true statement that the underlying search core that has been documented will not change dramatically, but stay the same and be further improved? Or am I misunderstanding?
4) UI documentation: after reading the compiled document, I changed my mind: a simple paragraph as "Components: User interface" could describe our current workflow and design choices, and links made to the files in docs/ui (which also need updating, I should upload the other mockups that I made).  I am thinking that this could drop in right below Search service, since the final paragraphs directly mention the UI templates and routes, and it would be a nice segue.

What do you think, @erickpeirson? Sorry for the back and forth on this.

**Comment by eawoods** [comment]
Oh almost forgot -- the bottom of the built documentation (HTML) says  "&copy;2017 Jane Bloggs." Is that something configurable?

**Comment by erickpeirson** [comment]
Oh Dr. Bloggs, so prolific. Yes, totally configurable :-)

**Comment by erickpeirson** [comment]
@eawoods Ok, ready when you are!

**Pull request merged**
